# Generated by Django 4.1.3 on 2023-02-01 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('datees', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Moviedetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=20)),
                ('release_date', models.CharField(max_length=20)),
                ('movie_screen', models.CharField(max_length=20)),
                ('time_am', models.CharField(max_length=20)),
                ('time_pm', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('details', models.CharField(max_length=20)),
                ('picture', models.ImageField(upload_to='movie/')),
            ],
        ),
        migrations.CreateModel(
            name='Tdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=20)),
                ('tname', models.CharField(max_length=20)),
                ('tscreen', models.CharField(max_length=20)),
                ('taddress', models.CharField(max_length=20)),
                ('tprice', models.CharField(max_length=20)),
                ('tuname', models.CharField(max_length=30)),
                ('temail', models.CharField(max_length=20)),
                ('tphone', models.BigIntegerField()),
                ('tpassword', models.CharField(max_length=30)),
                ('tgender', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Theater_screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_name', models.CharField(max_length=20)),
                ('seats', models.BigIntegerField()),
                ('theater', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='towner.tdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Towner_seats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.CharField(default='', max_length=20)),
                ('status', models.CharField(default='Vacant', max_length=20)),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='towner.theater_screen')),
            ],
        ),
        migrations.CreateModel(
            name='time_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_one', models.CharField(max_length=20)),
                ('time_two', models.CharField(max_length=20)),
                ('time_three', models.CharField(max_length=20)),
                ('gender', models.CharField(default='', max_length=20)),
                ('language', models.CharField(default='', max_length=20)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='towner.date')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='towner.moviedetails')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='towner.theater_screen')),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='towner.tdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Theater_seats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='towner.theater_screen')),
            ],
        ),
        migrations.CreateModel(
            name='SeatsName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.CharField(default='', max_length=20)),
                ('status', models.CharField(default='Vacant', max_length=20)),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='towner.theater_screen')),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='towner.tdetails')),
            ],
        ),
        migrations.CreateModel(
            name='SeatInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seatname', models.CharField(max_length=20)),
                ('noofseats', models.CharField(max_length=20)),
                ('rupes', models.CharField(max_length=20)),
                ('customer', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='towner.tdetails')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='towner.time_table')),
            ],
        ),
        migrations.AddField(
            model_name='moviedetails',
            name='theater',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='towner.tdetails'),
        ),
    ]
