# Generated by Django 4.1.3 on 2023-02-01 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('towner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatsname',
            name='theater',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='towner.tdetails'),
        ),
    ]
