# Generated by Django 4.1.3 on 2023-02-01 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('towner', '0002_alter_seatsname_theater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatsname',
            name='theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='towner.tdetails'),
        ),
        migrations.CreateModel(
            name='Seatdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.CharField(default='', max_length=20)),
                ('status', models.CharField(default='Vacant', max_length=20)),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='towner.theater_screen')),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='towner.tdetails')),
            ],
        ),
    ]
