# Generated by Django 4.1.3 on 2023-02-02 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('towner', '0003_alter_seatsname_theater_seatdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seatinfo',
            name='seatname',
        ),
        migrations.AddField(
            model_name='seatinfo',
            name='seat',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='towner.seatdetails'),
        ),
        migrations.CreateModel(
            name='BookingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noofseats', models.CharField(max_length=20)),
                ('rupes', models.CharField(max_length=20)),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='towner.time_table')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noofseats', models.CharField(max_length=20)),
                ('amount', models.CharField(max_length=20)),
                ('customer', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='towner.tdetails')),
                ('seat', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='towner.seatdetails')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='towner.time_table')),
            ],
        ),
    ]
