# Generated by Django 4.1.3 on 2023-02-13 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('towner', '0007_remove_moviedetails_time_am_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time_table',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='time_table',
            name='language',
        ),
    ]
