# Generated by Django 4.1.3 on 2023-02-13 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('towner', '0008_remove_time_table_gender_remove_time_table_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviedetails',
            old_name='gender',
            new_name='general',
        ),
    ]
