# Generated by Django 4.1.3 on 2023-02-23 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('towner', '0010_bookingdetails_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviedetails',
            name='price',
        ),
    ]
