# Generated by Django 4.1.3 on 2023-02-23 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('towner', '0011_remove_moviedetails_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tdetails',
            name='tprice',
        ),
    ]
