# Generated by Django 4.1.3 on 2022-12-07 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('uemail', models.CharField(max_length=20)),
                ('uphone', models.BigIntegerField()),
                ('password', models.CharField(max_length=30)),
                ('udob', models.CharField(max_length=20)),
                ('ugender', models.CharField(max_length=20)),
            ],
        ),
    ]
