# Generated by Django 4.1.3 on 2022-12-07 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0003_alter_userdetails_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userdetails',
            table='user_user',
        ),
    ]
